awslabs/aws-crt-swift

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift
*Description of changes:* This PR updates the signing config to have the correct default value for the SignedBodyHeader to be `.none`.
=> Update signing config default

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift
*Description of changes:* This PR fixes a bug where the should sign header function is not nil and thus the pointer to it should not be nil.
=> fix: correct should sign header pointer being nil

Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift, Source/AwsCommonRuntimeKit/io/Stream.swift
*Description of changes:* This PR adds needed extensions to use `ByteBuffer` in streaming in the sdk
=> fix: add codable conformance to byte buffer plus extension

.github/workflows/ci.yml, CONTRIBUTING.md
*Description of changes:* Update CI to use Main as default branch changes to Main.
=> chore: update ci to main from master

Source/AwsCommonRuntimeKit/auth/credentials/CRTAWSCredentialsProvider.swift
*Description of changes:* Correct issue where in order to get a profile cred provider, you were forced to pass in the names of your config and cred files even if it was the default ones.
=> fix:  bug where you have to pass all three params to use profile cred provider

Source/AwsCommonRuntimeKit/auth/credentials/CRTAWSCredentialsProvider.swift, Source/AwsCommonRuntimeKit/auth/credentials/CRTCredentialsProviderStaticConfig.swift, Test/AwsCommonRuntimeKitTests/auth/AWSCredentialsProviderTests.swift
*Description of changes:* Session token should be optional to pass. correct behavior for static credentials provider
=> fix: static credetnials provider

Source/AwsCommonRuntimeKit/Utilities.swift, Source/AwsCommonRuntimeKit/auth/credentials/CRTAWSCredentialsProvider.swift, Source/AwsCommonRuntimeKit/auth/credentials/CRTCredentialsProvider.swift, Source/AwsCommonRuntimeKit/auth/signing/SigV4HttpRequestSigner.swift, Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift, Source/AwsCommonRuntimeKit/crt/AWSDate.swift, Source/AwsCommonRuntimeKit/crt/Atomic.swift, Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift, Source/AwsCommonRuntimeKit/crt/ShutDownCallbackOptions.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnection.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnectionManager.swift, Source/AwsCommonRuntimeKit/http/HttpMonitoringOptions.swift, Source/AwsCommonRuntimeKit/http/HttpProxyOptions.swift, Source/AwsCommonRuntimeKit/io/ClientBootstrap.swift, Source/AwsCommonRuntimeKit/io/EventLoopGroup.swift, Source/AwsCommonRuntimeKit/io/HostResolver.swift, Source/AwsCommonRuntimeKit/io/SocketOptions.swift, Source/AwsCommonRuntimeKit/io/Stream.swift, Source/AwsCommonRuntimeKit/io/TlsConnectionOptions.swift, Source/AwsCommonRuntimeKit/io/TlsContextOptions.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTAWSRetryStrategy.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTAWSRetryToken.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTRetryStrategy.swift, Source/AwsCommonRuntimeKit/mqtt/MqttConnection.swift
*Description of changes:* This PR refactors the way pointers are created and initialized in Swift to protect against cases where the pointer is created but uninitialized later causing a seg fault when the c code calls back into the Swift code.
=> fix: refactor pointer creation to protect against improper init

Package.swift
This PR adds an additional exclude needed in order to compile on m1 macs (arm). This closes a customer issue in the Swift SDK: https://github.com/awslabs/aws-sdk-swift/issues/392
=> fix: m1 build

Source/AwsCommonRuntimeKit/io/TlsConnectionOptions.swift
*Description of changes:* This adjusts the tls negotiation timeout per Zoe's new SEP.
=> fix: adjust default tls negotiation timeouts for mobile and otherwise

.github/workflows/ci.yml, Package.swift, builder.json
=> feat: build for watchos and tvos

Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift
*Description of changes:* when streaming more than 4096 bytes, the stream was in an indefinite loop of reading as the index wasn't being properly moved and new chunks were not being read off the stream.
This closes https://github.com/awslabs/aws-sdk-swift/issues/531
=> fix: indefinite streaming loop

Source/AwsCommonRuntimeKit/io/AddressRecordType.swift, Source/AwsCommonRuntimeKit/io/HostAddress.swift, Source/AwsCommonRuntimeKit/io/HostResolver.swift
*Description of changes:* This PR adds a new swift type that copies over the host address fields in order to hold onto them since c lets them go at an indeterminate time.
=> fix: add host address struct to copy over fields from c

Package.swift
*Issue #*
Fixes https://github.com/awslabs/aws-sdk-swift/issues/680
Change the declared name of this package to match its inferred name (i.e. the last path component of its Git URL, minus the extension).  This is being performed in conjunction with similar renames of `aws-sdk-swift` and `smithy-swift`.  A complete rationale for making this change is given in [this PR](https://github.com/awslabs/aws-sdk-swift/pull/678).
**This is a breaking change** but consumers of this package simply need to update their `Package.swift` to refer to the package by the new name.
=> fix!: Rename package to match name inferred from git URL

Source/AwsCommonRuntimeKit/io/retryer/RetryStrategy.swift, Test/AwsCommonRuntimeKitTests/io/RetryerTests.swift
- Update Sechdule retry api to return retry token
=> Update schedule retry API to return retry token

Source/AwsCommonRuntimeKit/auth/credentials/Credentials.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsTests.swift
=> Fix: Credential's Expiration time

Source/AwsCommonRuntimeKit/event-stream/EventStreamHeader.swift, Source/AwsCommonRuntimeKit/event-stream/EventStreamMessage.swift, Source/AwsCommonRuntimeKit/http/HTTPMessage.swift, Source/AwsCommonRuntimeKit/http/HTTPRequest.swift, Source/AwsCommonRuntimeKit/io/StreamCore.swift
- C APIs store a pointer to input stream. Use an actual pointer to fix undefined behavior as storing pointers generated by & is not valid.
-  Adds public struct initializers because auto generated struct initializers have an internal scope.
=> Fix input stream

Source/AwsCommonRuntimeKit/http/HTTP2Stream.swift, Source/AwsCommonRuntimeKit/http/HTTPHeaderBlock.swift, Source/AwsCommonRuntimeKit/http/HTTPRequestOptions.swift, Source/AwsCommonRuntimeKit/http/HTTPStream.swift, Source/AwsCommonRuntimeKit/http/HTTPStreamCallbackCore.swift, Source/Elasticurl/Elasticurl.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2ClientConnectionTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2StreamManagerTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientTestFixture.swift
- Removes Stream pointer from HTTP callbacks which complicates overall logic due to cyclic dependency without providing much value.
=> Remove HTTPStream from HTTP callbacks

Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Source/AwsCommonRuntimeKit/crt/ShutdownCallbackCore.swift, Source/AwsCommonRuntimeKit/crt/Utilities.swift, Source/AwsCommonRuntimeKit/event-stream/EventStreamHeader.swift, Source/AwsCommonRuntimeKit/event-stream/EventStreamMessage.swift, Source/AwsCommonRuntimeKit/http/HTTPMessage.swift, Source/AwsCommonRuntimeKit/http/HTTPRequest.swift, Source/AwsCommonRuntimeKit/io/StreamCore.swift, Source/AwsCommonRuntimeKit/io/retryer/RetryStrategy.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift, Test/AwsCommonRuntimeKitTests/io/RetryerTests.swift
Issue #127 
- Expose generateRandom as a non-C closure after relevant changes in C
- A new pattern for to retain callbacks until shutdown callback has fired which doesn't require double retain/release.
=> Fix generate random callback

Source/AwsCommonRuntimeKit/CommonRuntimeKit.swift, Source/AwsCommonRuntimeKit/crt/Allocator.swift, Test/AwsCommonRuntimeKitTests/XCBaseTestCase.swift, Test/AwsCommonRuntimeKitTests/auth/ChunkSignerTests.swift
- Always override defaultAllocator with tracingAllocator in tests. I would have preferred to make it internal, but it needs to be public to override in tests `onSetup`.
- Add documentation for `CommonRuntimeKit` and warn users about the dangers of cleanup.
=> Override Default Allocator

Package.swift
https://github.com/awslabs/aws-crt-swift/issues/159
The Package.swift file is compiled at compile-time, and SwiftPM is not yet mature enough to handle complex cross-compilations. Remove the #if directive for the architecture. This particular #if directive wouldn't have created an issue because:
- We always excluded the intel folder.
- For ARM, in the C code, we only have a runtime check for Linux and BSD.
=> Remove arch based conditionals

Package.swift
#163 
- S2N has removed the module.modulemap which was conflicting with the Swift's generated module.modulemap. Update the module name so that it doesn't conflict with `s2n.h` on case insensitive system.
=> Fix S2N build on Linux

.github/workflows/ci.yml
This makes malicious pull requests harder to pull off. CI won't run unless code is pushed to THIS repo, which only team members can do.
=> Change CI to Push

Package.swift, Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Test/AwsCommonRuntimeKitTests/Resources/example_profile.txt, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift, Test/AwsCommonRuntimeKitTests/sdkutils/FileBasedConfigurationTests.swift
=> Process Credentials Provider

Package.swift, Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift
#174 
- Make auth token optional
- Host & PathandQuery is required as the C implementation does not read the env variables for now.
=> Fix ECSCredentialsProvider to Make AuthToken Optional

Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Source/AwsCommonRuntimeKit/crt/Utilities.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift
#175 
- Exposes additional API for STSWebIdentity so that customers can pass required values as parameters.
=> Add parameters for StsWebIdentity

aws-common-runtime/config/aws/common/config.h
Stop using private OS APIs on ALL builds, not just iOS.
Related: https://github.com/awslabs/aws-c-cal/pull/171
=> App Store fix, take 2

Package.swift, Source/AwsCommonRuntimeKit/crt/Checksums.swift, Source/AwsCommonRuntimeKit/crt/Hash.swift, Source/AwsCommonRuntimeKit/crt/Utilities.swift, Test/AwsCommonRuntimeKitTests/crt/ChecksumsTests.swift, Test/AwsCommonRuntimeKitTests/crt/HashTests.swift, Test/AwsCommonRuntimeKitTests/crt/UtilityTests.swift
Issue: https://github.com/awslabs/aws-crt-swift/issues/198
=> Bind Sha1, crc32 and crc32c 

.github/workflows/ci.yml, Package.swift
#204 
- Bump minimum Swift version to 5.7
=> Drop Support for Swift 5.5 and 5.6

Source/AwsCommonRuntimeKit/http/HTTP1Stream.swift, Source/AwsCommonRuntimeKit/http/HTTP2Stream.swift, Source/AwsCommonRuntimeKit/http/HTTPStream.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2ClientConnectionTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2StreamManagerTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientTestFixture.swift, Test/AwsCommonRuntimeKitTests/http/HTTPTests.swift
#218 
- Adds support for writeChunk API in HTTP1.
- Adds unified writeChunk in HTTStream base class. 
- Update tests to use postman-echo instead of httpbin.
=> WriteChunk API for HTTP1

Source/AwsCommonRuntimeKit/crt/Utilities.swift
=> Fix String Decode Crash

Package.swift
#210 
- Improves documentation around why we have disabled the hardware-accelerated checksum in Swift.
=> Improves documentation in Package.swift regarding lack of CPU flags.

.github/workflows/stale_issue.yml
We received customer feedback that our stale issue timings are too tight. This doubles what we had previously.
=> chore: relax stale issue timings

.swiftlint.yml, Source/AwsCommonRuntimeKit/mqtt/Mqtt5Client.swift, Source/AwsCommonRuntimeKit/mqtt/Mqtt5Options.swift, Source/AwsCommonRuntimeKit/mqtt/Mqtt5Packets.swift
Initialize packets using a convenience init() instead of a static function.
=> Mqtt5 Init From Pointer

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift, Test/AwsCommonRuntimeKitTests/auth/SigningConfigTests.swift
*Issue #:*
[#1331](https://github.com/awslabs/aws-sdk-swift/issues/1331)
Dependent PRs to consume updated crt version:
- https://github.com/smithy-lang/smithy-swift/pull/767
- https://github.com/awslabs/aws-sdk-swift/pull/1590
- Convert SignedBodyValue from enum: String to enum: CustomStringConvertible, Equatable to allow for pre-calculated SHA256 as intended
=> feat: change SignedBodyValue enum to allow precomputed sha256 hash

Package.swift, Source/AwsCommonRuntimeKit/http/HTTP2StreamManager.swift, Source/AwsCommonRuntimeKit/http/HTTPClientConnectionManager.swift, Source/AwsCommonRuntimeKit/http/HTTPClientConnectionManagerMetrics.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2StreamManagerTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPTests.swift
https://github.com/awslabs/aws-crt-swift/pull/272
*Related to: https://github.com/smithy-lang/smithy-swift/pull/735, https://github.com/awslabs/aws-sdk-swift/pull/1582*
For the AWS SDK for Swift Observability changes, using the `fetch_metrics()` APIs for the HTTP connection managers is needed.
=> feat: Add `fetch_metrics()` for HTTP connection managers

.github/workflows/ci.yml, Source/AwsCommonRuntimeKit/crt/Utilities.swift, Source/AwsCommonRuntimeKit/sdkutils/endpoint/EndpointsRequestContext.swift, Test/AwsCommonRuntimeKitTests/crt/Utilities.swift, Test/AwsCommonRuntimeKitTests/sdkutils/EndpointsRuleEngineTests.swift
=> Add string array as an option for request context params for endpoint resolution

Source/AwsCommonRuntimeKit/crt/Checksums.swift, Test/AwsCommonRuntimeKitTests/crt/ChecksumsTests.swift
=> Bind CRC64

.github/workflows/s2n-prelude-changes.yml, Package.swift, aws-common-runtime/config/aws/common/config.h
S2N added a new `s2n_prelude.h`, which is included in all .c files when building S2N using the compiler flag `-include`.
See: https://github.com/aws/s2n-tls/pull/4465
Since SwiftPM does not yet support compiler flags, we are defining all the macros from `s2n_prelude.h` manually. We have also added a CI job to ensure that whenever `s2n_prelude.h` changes, we can detect and update `Package.swift` accordingly.
=> Fix for s2n_prelude.h Changes 

.github/workflows/ci.yml, Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift
- Fix sts provider
- Remove macos-12 runner since it's deprecated https://github.com/actions/runner-images/issues/10721
=> Fix STSCredentialsProvider

.github/workflows/ci.yml
=> Switch CI to using Roles

Source/AwsCommonRuntimeKit/auth/credentials/Credentials.swift, Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Source/AwsCommonRuntimeKit/crt/ContinuationCore.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsTests.swift
- An optional-String `accountId` field is added to the `Credentials` type
- The `CredentialsProvider` is modified to allow for creation with an optional-param account ID
- Tests for credentials & credentials providers are modified to verify operation of the account ID field.
These changes are intended to be temporary.  A new public API for passing account ID into `CredentialsProvider` at creation is protected with `@_spi()` so that customers do not rely on it for permanent use.
=> feat: Add support for accountId field on Credentials & CredentialsProvider

Source/AwsCommonRuntimeKit/sdkutils/FileBasedConfiguration.swift, Test/AwsCommonRuntimeKitTests/Resources/example_profile.txt, Test/AwsCommonRuntimeKitTests/sdkutils/FileBasedConfigurationTests.swift
=> Update Config File Parsing Logic to Parse Services Section

Source/AwsCommonRuntimeKit/mqtt/Mqtt5Client.swift, Test/AwsCommonRuntimeKitTests/mqtt/Mqtt5ClientTests.swift
Removed `async` from all callback type-aliases for the MQTT5 client. Instead of being scheduled in their own task block for execution, they will now be handled directly on the CRT I/O thread (eventloop).
=> Make Mqtt5 client callbacks synchronous

Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift
- Data.startIndex doesn't start with 0 if the Data is a slice in a larger portion. Use endIndex instead. 
=> Fix ByteBuffer End of Stream Bug 

Test/AwsCommonRuntimeKitTests/http/HTTP2ClientConnectionTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2StreamManagerTests.swift, Test/AwsCommonRuntimeKitTests/io/StreamTests.swift
- httpbin.org is flaky and abandoned. Move to postman-echo.com. Similar to https://github.com/awslabs/aws-crt-java/pull/627
- Add a test for isEndOfStream. This is a follow up from #334.
=> Fix Flaky Tests

.github/workflows/ci.yml, .gitignore, Package.swift
- AWS Swift SDK minimum version is Swift 5.9 now. 
- I am working on integrating with [Swift-Format](https://github.com/swiftlang/swift-format) which has some changes in Swift 5.8 which will be good to have.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> Bump minimum Swift version to 5.9

Package.swift, Source/Canary/Mqtt5Canary/Mqtt5Canary.swift
=> Mqtt5 Canary Application
