Package.swift, README.md, Source/AwsCommonRuntimeKit/AwsCommonRuntimeKit.swift, Source/AwsCommonRuntimeKit/io/TlsConnectionOptions.swift, Source/AwsCommonRuntimeKit/io/TlsContextOptions.swift
*Description of changes:* Code Review Requests from @JonathanHenson 
=> Late Code Review changes

Source/AwsCommonRuntimeKit/auth/credentials/AWSCredentialsProvider.swift
*Description of changes:* fix access modifier of aws creds provider
=> fix modifier access of credentials provider

Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift
*Description of changes:* Removing warnings from Xcode
=> remove warnings

Source/AwsCommonRuntimeKit/crt/Future.swift, Test/AwsCommonRuntimeKitTests/crt/FutureTests.swift
*Description of changes:* Added single extension function on a group of futures
=> Adding Future Extension to track completion of a Future array

Package.swift
*Description of changes:* Update swift tools version to 5.3
=> update swift tools version

.github/workflows/ci.yml
*Description of changes:* Update Version of the CRT builder for latest CI
=> Update Version of the CRT builder for latest CI

Source/AwsCommonRuntimeKit/http/CRTHttpResponse.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTAWSRetryStrategy.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTRetryError.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTRetryStrategy.swift
*Description of changes:* Fix the naming collisions with the SDK
=> fix: naming collisions

Package.swift
=> chore: remove unsafe cflags v2

Source/AwsCommonRuntimeKit/io/Stream.swift
*Description of changes:* This PR updates the cal package to remove the lib crypto symbol warnings and also removes the stream build warnings.
=> fix: remove stream warning and update cal

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift
*Description of changes:* Fixes Seg fault on signing
=> fix: signing seg fault

Source/Elasticurl/main.swift
*Description of changes:* this removes a logger warning
=> fix: remove logger warning

Source/AwsCommonRuntimeKit/auth/credentials/CRTAWSCredentialsProvider.swift, Source/AwsCommonRuntimeKit/auth/credentials/CRTCredentialsProvider.swift
*Description of changes:* This PR fixes the custom credentials provider pathway for a customer. It was completely broken before.
=> fix: customcredprovider

Source/AwsCommonRuntimeKit/Utilities.swift, Test/AwsCommonRuntimeKitTests/crt/UtilityTests.swift
*Description of changes:* Exposes md5 function
=> feat: expose md5 function

Source/AwsCommonRuntimeKit/Utilities.swift, Test/AwsCommonRuntimeKitTests/crt/UtilityTests.swift
*Description of changes:* Adds sha256 checksum extension on a string for calculations in middleware in the sdk
=> feat: add sha256 checksum extension

Source/AwsCommonRuntimeKit/Utilities.swift, Source/AwsCommonRuntimeKit/mqtt/MqttConnection.swift
=> fix: mqtt connection bugs

Package.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnectionManager.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnectionOptions.swift, Source/AwsCommonRuntimeKit/http/HttpMonitoringOptions.swift, Source/AwsCommonRuntimeKit/http/HttpProxyConnectionType.swift, Source/AwsCommonRuntimeKit/http/HttpProxyEnvType.swift, Source/AwsCommonRuntimeKit/http/ProxyEnvSettings.swift, latest_submodules.py
*Description of changes:* This PR updates all crt git submodules and fixes any build or api issues that came along with that. Also adds a handy script from @graebm to update submodules easily
=> fix: update submodules to latest versions

Source/AwsCommonRuntimeKit/http/HttpMessage.swift
Corresponding PRs: https://github.com/awslabs/smithy-swift/pull/409 & https://github.com/awslabs/aws-sdk-swift/pull/552
=> fix: headercount runtime issue

Package.swift
This should help expose bugs faster
=> Turn on asserts in C code when building Debug

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> Add new Issue templates

.github/workflows/ci.yml, .swiftlint.yml, Package.swift, Source/AwsCommonRuntimeKit/auth/credentials/CRTAWSCredentialsProvider.swift, Source/AwsCommonRuntimeKit/auth/imds/CRTIMDSClient.swift, Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift, Source/AwsCommonRuntimeKit/crt/CommandLine.swift, Source/AwsCommonRuntimeKit/crt/Future.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnection.swift, Source/AwsCommonRuntimeKit/http/HttpClientConnectionManager.swift, Source/AwsCommonRuntimeKit/http/HttpHeaders.swift, Source/AwsCommonRuntimeKit/http/HttpMessage.swift, Source/AwsCommonRuntimeKit/http/HttpStream.swift, Source/AwsCommonRuntimeKit/io/ClientBootstrap.swift, Source/AwsCommonRuntimeKit/io/Stream.swift, Source/AwsCommonRuntimeKit/io/TlsContextOptions.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTAWSRetryStrategy.swift, Source/AwsCommonRuntimeKit/io/retryer/CRTRetryStrategy.swift, Source/AwsCommonRuntimeKit/mqtt/MqttClient.swift, Source/AwsCommonRuntimeKit/mqtt/MqttConnection.swift, Source/AwsCommonRuntimeKit/sdkutils/CRTAWSEndpointsRuleEngine.swift, Source/AwsCommonRuntimeKit/sdkutils/EndpointProperty.swift, Source/Elasticurl/Elasticurl.swift, Source/Elasticurl/ElasticurlOptions.swift
This PR updates our swiftlint config to match our sconfigs defined in smithy-swift and aws-sdk-swift repos.
Additionally, this updates our swiftlint github action
=> chore: Updates swiftlint and updates config to match other swift-sdk repos

Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Source/AwsCommonRuntimeKit/crt/ByteBuffer.swift, Source/AwsCommonRuntimeKit/crt/Utilities.swift
This PR contains various tweaks that make it easier for the aws-sdk-swift repo to update to version 0.5.0+
=> fix: Various fixes to help aws-swift-sdk update to 0.5.0+

Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift
Issue #133 
- Add the missing bootstrap option in Profile credentials provider
=> Fix Profile Credentials Provider

Source/AwsCommonRuntimeKit/io/TLSContextOptions.swift
- Adds option to set minimum tls version in tls context
=> Bind minimum tls version

Package.swift
=> [fix][0.5.8] Disable hardware acceleration

Package.swift
- Disable hardware accelaration
=> [main] Disable hardware acceleration

Source/AwsCommonRuntimeKit/auth/signing/Signer.swift, Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift, Source/AwsCommonRuntimeKit/event-stream/EventStreamMessageDecoder.swift
*Issue #156*
- Adds an signEvent function
=> Adds Event Signer

Source/AwsCommonRuntimeKit/http/HTTPRequestOptions.swift, Source/AwsCommonRuntimeKit/http/HTTPStreamCallbackCore.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientTestFixture.swift
Companion for https://github.com/awslabs/smithy-swift/pull/530
=> refactor: streams

README.md
- Add a preview warning in readme
=> Add preview warning

.swiftlint.yml, Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift, Test/AwsCommonRuntimeKitTests/Resources/example_sso_profile.txt, Test/AwsCommonRuntimeKitTests/auth/CredentialsProviderTests.swift
- #95 
- Adds SSOCredentialsProvider support
=> Adds SSOCredentialsProvider

Package.swift
- This PR reformats the Package.swift file to include sections for each repo, which improves readability and makes it easier to review any changes made in future to fix iOS.
- This PR doesn't contain any intended code changes
=> Reformat package.swift

Package.swift
- Latest submodules with fixes to properly exclude platform_info.c code.
=> Fix Package.Swift for Latest Submodules

Source/AwsCommonRuntimeKit/http/HTTP2StreamManagerOptions.swift, Source/AwsCommonRuntimeKit/http/HTTPClientConnectionOptions.swift, Source/AwsCommonRuntimeKit/http/HTTPProxyOptions.swift, Source/Elasticurl/Elasticurl.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2StreamManagerTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientConnectionManagerTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientConnectionOptionsTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientTestFixture.swift, Test/AwsCommonRuntimeKitTests/http/HTTPProxyTests.swift
- Updates port from UInt16 to UInt32 to keep it consistent with the C layer and support VSOCK.
=> Update Port to 32Bit

Source/AwsCommonRuntimeKit/crt/Checksums.swift, Source/AwsCommonRuntimeKit/crt/Hash.swift, Test/AwsCommonRuntimeKitTests/crt/ChecksumsTests.swift, Test/AwsCommonRuntimeKitTests/crt/HashTests.swift, Test/AwsCommonRuntimeKitTests/http/HTTP2ClientConnectionTests.swift
- Change MD5 function to operate over data instead of String to avoid any encoding/decoding issues and just operate on arbitrary bytes.
=> Fix MD5 to operate over data

Source/AwsCommonRuntimeKit/http/HTTP2StreamManagerOptions.swift, Source/AwsCommonRuntimeKit/http/HTTPClientConnectionOptions.swift
=> Improve documentation to create HTTP connections

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift
=> feat: add STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER support

Source/AwsCommonRuntimeKit/http/HTTPMonitoringOptions.swift, Test/AwsCommonRuntimeKitTests/http/HTTPClientConnectionOptionsTests.swift
=> Fix MonitoringOptions

codebuild/linux-integration-tests.sh, codebuild/linux-integration-tests.yml
Update codebuild script using crt-builder so that it set the test env var correctly. 
=> Update Codebuild to use crt-builder

Source/AwsCommonRuntimeKit/io/TLSContextOptions.swift, Test/AwsCommonRuntimeKitTests/io/TLSContextTests.swift, Test/AwsCommonRuntimeKitTests/sdkutils/FileBasedConfigurationTests.swift
=> Fix: TLS API update & unit test fix

Source/AwsCommonRuntimeKit/crt/Lock.swift, Source/AwsCommonRuntimeKit/mqtt/Mqtt5Client.swift, Source/AwsCommonRuntimeKit/mqtt/Mqtt5Types.swift
=> Mqtt5 Callback Lock

Source/AwsCommonRuntimeKit/crt/CBOR.swift, Test/AwsCommonRuntimeKitTests/crt/CBOR.swift
- Added support for indefinite object decoding
- Refactored during debugging
=> feat: Refactor CBOR bindings and add support for indefinite object decoding

Source/AwsCommonRuntimeKit/auth/signing/SigningConfig.swift
**Description of changes:*
Bind S3Express signer type for S3Express
=> Add S3Express Signer type

Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift
=> Fix docs for CredentialsProviders

Package.swift
latest sub-modules to pull in https://github.com/awslabs/aws-c-event-stream/pull/125. 
=> latest submodules

Source/AwsCommonRuntimeKit/mqtt/Mqtt5Client.swift
=> Mark OnWebSocketHandshakeInterceptComplete as Sendable
